#!/bin/bash
#plot "$1" smooth csplines lc rgb "#0055ff", \
#    "$1" lc rgb "magenta"

#plot "$1", "$1" smooth csplines lc rgb "#0055ff",\
#     "$2", "$2" smooth csplines lc rgb "#555500", \
#     "$3", "$3" smooth csplines ,\
#     "$4", "$4" smooth csplines
gnuplot << EOF
set terminal png
set output "missrate_all.png"
set title "Missrate"
set grid
set xtics("2x16K" 1, "4x16K" 2, "4x32K" 3, "8x32K" 4, "4x64K" 5, "8x64K" 6)
set xlabel "Assocciativity x Cache Size"
set ylabel "miss-rate"
plot "$1" title "art" smooth csplines ,"$1" notitle,\
     "$2" title "equake" smooth csplines ,"$2" notitle,\
     "$3" title "gzip" smooth csplines ,"$3" notitle,\
     "$4" title "mcf" smooth csplines ,"$4" notitle
EOF

