#!/bin/bash

t1=`echo $1 | cut -d. -f2`
t2=`echo $2 | cut -d. -f2`
t3=`echo $3 | cut -d. -f2`
t4=`echo $4 | cut -d. -f2`
t5=`echo $5 | cut -d. -f2`
t6=`echo $6 | cut -d. -f2`




gnuplot << EOF
set terminal png size 1024, 768
set output "results_B1_direction.png"
set title "btb predictor direction"
set key right outside top
set grid
set xtics("512x1" 1, "256x2" 2, "128x4" 3, "64x8" 4)
set xlabel "predictor specs"

plot "$1" title '$t1' ,"$1" with lines notitle ,\
     "$2" title '$t2' ,"$2" with lines notitle ,\
     "$3" title '$t3' ,"$3" with lines notitle ,\
     "$4" title '$t4' ,"$4" with lines notitle ,\
     "$5" title '$t5' ,"$5" with lines notitle ,\
     "$6" title '$t6' ,"$6" with lines notitle 

set output "results_B1_target.png"
set title "btb predictor target"
set key right outside top
set grid
set xtics("512x1" 1, "256x2" 2, "128x4" 3, "64x8" 4)
set xlabel "predictor specs"

plot "$1" using 1:3 title '$t1' ,"$1" using 1:3 with lines notitle ,\
     "$2" using 1:3 title '$t2' ,"$2" using 1:3 with lines notitle ,\
     "$3" using 1:3 title '$t3' ,"$3" using 1:3 with lines notitle ,\
     "$4" using 1:3 title '$t4' ,"$4" using 1:3 with lines notitle ,\
     "$5" using 1:3 title '$t5' ,"$5" using 1:3 with lines notitle ,\
     "$6" using 1:3 title '$t6' ,"$6" using 1:3 with lines notitle 

EOF

