#!/bin/bash
gnuplot << EOF
set terminal png size 1024, 768
set output "results_B1_direction.png"
set title "btb predictor direction"
set key right outside top
set grid
set xtics("512x1" 1, "256x2" 2, "128x4" 3, "64x8" 4)
set xlabel "predictor specs"


plot "$1" ,"$1" with lines notitle ,\
     "$2" ,"$2" with lines notitle ,\
     "$3" ,"$3" with lines notitle ,\
     "$4" ,"$4" with lines notitle ,\
     "$5" ,"$5" with lines notitle ,\
     "$6" ,"$6" with lines notitle 

EOF

gnuplot << EOF
set output "results_B1_target.png"
set title "btb predictor direction"
set key right outside top
set grid
set xtics("512x1" 1, "256x2" 2, "128x4" 3, "64x8" 4)
set xlabel "predictor specs"

plot "$1" using 1:3 ,"$1" using 1:3 with lines notitle ,\
     "$2" using 1:3 ,"$2" using 1:3 with lines notitle ,\
     "$3" using 1:3 ,"$3" using 1:3 with lines notitle ,\
     "$4" using 1:3 ,"$4" using 1:3 with lines notitle ,\
     "$5" using 1:3 ,"$5" using 1:3 with lines notitle ,\
     "$6" using 1:3 ,"$6" using 1:3 with lines notitle 

EOF

