#!/bin/bash
gnuplot << EOF
set terminal png size 1024, 768
set output "results_B1.png"
set title "btb predictor"
set key right outside top
set grid
set xtics("512x1" 1, "256x2" 2, "128x4" 3, "64x8" 4)
set xlabel "predictor specs"
set ylabel "MPKI"

plot "$1" w lp lw 2 ,\
     "$2" w lp lw 2 ,\
     "$3" w lp lw 2 ,\
     "$4" w lp lw 2 ,\
     "$5" w lp lw 2 ,\
     "$6" w lp lw 2 
EOF

