#!/bin/bash
#plot "$1" smooth csplines lc rgb "#0055ff", \
#    "$1" lc rgb "magenta"

#plot "$1", "$1" smooth csplines lc rgb "#0055ff",\
#     "$2", "$2" smooth csplines lc rgb "#555500", \
#     "$3", "$3" smooth csplines ,\
#     "$4", "$4" smooth csplines
gnuplot << EOF
set terminal png size 1024, 768
set output "ipc_all.png"
set title "IPC"
set key right outside top
set grid
set xtics("4x256K" 1, "4x512K" 2, "8x512K" 3, "8x1024K" 4, "16x1024K" 5, "8x2048K" 6, "16x2048K" 7)
set xlabel "Assocciativity x Cache Size"
set ylabel "IPC"

plot "$1" title "art" smooth csplines ,"$1" notitle,\
     "$2" title "equake" smooth csplines ,"$2" notitle,\
     "$3" title "gzip" smooth csplines ,"$3" notitle,\
     "$4" title "mcf" smooth csplines ,"$4" notitle
EOF

