#!/bin/bash

gnuplot << EOF
set terminal postscript enhanced "Helvetica" 16
set terminal png size 1536, 768
set output "ipc-l1-all.png"

set grid
set tmargin 5 
set xtics("2x16K" 1, "4x16K" 2, "4x32K" 3, "8x32K" 4, "4x64K" 5, "8x64K" 6)
set xlabel "Assocciativity x Cache Size"
set ylabel "IPC"
set multiplot layout 1,3 title "IPC for L1 cache" 
set yrange[0.00:0.14]
set nokey

set title "Line size: 64"
plot "art-ipc-l1-64.dat" u 1:3 title "art" w lp ,\
	 "gzip-ipc-l1-64.dat" u 1:3 title "gzip" w lp ,\
	 "mfc-ipc-l1-64.dat" u 1:3 title "mcf" w lp ,\
	 "equake-ipc-l1-64.dat" u 1:3 title "equake" w lp

set title "Line size: 32"
plot "art-ipc-l1-32.dat" u 1:3 title "art" w lp ,\
	 "gzip-ipc-l1-32.dat" u 1:3 title "gzip" w lp ,\
	 "mfc-ipc-l1-32.dat" u 1:3 title "mcf" w lp ,\
	 "equake-ipc-l1-32.dat" u 1:3 title "equake" w lp

set key at 6, 0.17
set key box 
set title "Line size: 128"
plot "art-ipc-l1-128.dat" u 1:3 title "art" w lp ,\
	 "gzip-ipc-l1-128.dat" u 1:3 title "gzip" w lp ,\
	 "mfc-ipc-l1-128.dat" u 1:3 title "mcf" w lp ,\
	 "equake-ipc-l1-128.dat" u 1:3 title "equake" w lp

set nomultiplot

EOF



