#!/bin/bash
gnuplot << EOF
set terminal png size 1024, 768
set output "results_A1.png"
set title "nbit predictor"
set key right outside top
set grid
set xlabel "predictor bits"
set ylabel "MPKI"

plot "$1" ,"$1" with lines notitle ,\
     "$2" ,"$2" with lines notitle ,\
     "$3" ,"$3" with lines notitle ,\
     "$4" ,"$4" with lines notitle ,\
     "$5" ,"$5" with lines notitle ,\
     "$6" ,"$6" with lines notitle 
EOF

