#!/bin/bash
#plot "$1" smooth csplines lc rgb "#0055ff", \
#    "$1" lc rgb "magenta"

#plot "$1", "$1" smooth csplines lc rgb "#0055ff",\
#     "$2", "$2" smooth csplines lc rgb "#555500", \
#     "$3", "$3" smooth csplines ,\
#     "$4", "$4" smooth csplines
#set xtics("i,j,k" 1, "i,k,j" 2, "j,i,k" 3, "j,k,i" 4, "k,i,j" 5, "k,j,i" 6)
gnuplot << EOF
set xtics ( "8"    0, "16"   1, "24"   2, "32"   3, "40"   4, "48"   5, "56"   6, "64"   7, "72"   8, "80"   9, "88"   10, "96"   11, "104"  12, "112"  13, "120"  14, "128"  15)



set terminal png size 1024, 768
set title "Cycles"
set grid
set xlabel "Block Size"
set ylabel "Cycles"

set output "cycles_hist.png"
plot "cycles.dat" with histogram lc 3 fs pattern 3 notitle
set output "cycles_hist2.png"
plot "cycles.dat" with histogram lc 3 fs pattern 1 notitle
set output "cycles_line.png"
plot "cycles.dat" with lines lc 2 notitle,\
    "cycles.dat" lc 2 notitle

set title "L1 Miss Rate"
set grid
set xlabel "Block Size"
set ylabel "Miss Rate"

set output "l1_miss_hist.png"
plot "l1.dat" with histogram lc 3 fs pattern 3 notitle
set output "l1_miss_hist2.png"
plot "l1.dat" with histogram lc 3 fs pattern 1 notitle
set output "l1_miss_line.png"
plot "l1.dat" with lines lc 2 notitle,\
    "l1.dat" lc 2 notitle

set title "L2 Miss Rate"
set grid
set xlabel "Block Size"
set ylabel "Miss Rate"

set output "l2_miss_hist.png"
plot "l2.dat" with histogram lc 3 fs pattern 3 notitle
set output "l2_miss_hist2.png"
plot "l2.dat" with histogram lc 3 fs pattern 1 notitle
set output "l2_miss_line.png"
plot "l2.dat" with lines lc 2 notitle,\
    "l2.dat" lc 2 notitle

EOF

