
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the workspace setup script.

SIMICS_MODEL_BUILDER=/home/master/simics/simics-model-builder-4.0.17
SIMICS_BASE=/home/master/simics/simics-4.0.63
SIMICS_WORKSPACE=/home/master/Repos/adv-comparch/simics-workspace
PYTHON=$(SIMICS_WORKSPACE)/bin/mini-python

INCLUDE_PATHS = /home/master/simics/simics-4.0.63/src/include:/home/master/simics/simics-model-builder-4.0.17/src/include

# Put user definitions in config-user.mk
-include config-user.mk

# allow user to override HOST_TYPE
ifeq (,$(HOST_TYPE))
 HOST_TYPE:=$(shell $(PYTHON) $(SIMICS_BASE)/scripts/host_type.py)
endif

include compiler.mk

include $(SIMICS_MODEL_BUILDER)/config/workspace/config.mk

