#!/bin/sh
# this file will be overwritten by the workspace setup script
SIMICS_BASE_PACKAGE="/home/master/simics/simics-4.0.63"
export SIMICS_BASE_PACKAGE
if [ -f "/home/master/Repos/adv-comparch/simics-workspace/.package-list" ]; then
    exec "/home/master/simics/simics-4.0.63/bin/simics" -package-list "/home/master/Repos/adv-comparch/simics-workspace/.package-list" -workspace "/home/master/Repos/adv-comparch/simics-workspace" ${1+"$@"}
else
    exec "/home/master/simics/simics-4.0.63/bin/simics" -workspace "/home/master/Repos/adv-comparch/simics-workspace" ${1+"$@"}
fi
