#!/bin/bash
#plot "$1" smooth csplines lc rgb "#0055ff", \
#    "$1" lc rgb "magenta"

#plot "$1", "$1" smooth csplines lc rgb "#0055ff",\
#     "$2", "$2" smooth csplines lc rgb "#555500", \
#     "$3", "$3" smooth csplines ,\
#     "$4", "$4" smooth csplines
gnuplot << EOF
set terminal png size 1024,768
set output "missrate_all.png"
plot "$1" smooth csplines ,"$1" notitle,\
     "$2" smooth csplines ,"$2" notitle,\
     "$3" smooth csplines ,"$3" notitle,\
     "$4" smooth csplines ,"$4" notitle
EOF

